name: Notify Forks

on:
    push:
        branches:
            - main

jobs:
    notify:
        runs-on: ubuntu-latest
        steps:
            - name: Repository Dispatch
              uses: peter-evans/repository-dispatch@v2
              with:
                  token: ${{ secrets.PAT_TOKEN }}
                  repository: SahooBishwajeet/alumni-portal-backend
                  event-type: sync-fork
